### ISSUE TITLE
Didn't succeed in installing pyforest

### ISSUE THREAD

**Issue by alon1samuel** [8080labs/pyforest#45]
### Environment

* Operating System: ubuntu 18.04
* Python Version: 3.9.0
* How did you install pyforest: pip install --upgrade pyforest
* Python packages: conda list:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
ca-certificates           2021.5.25            h06a4308_1  
certifi                   2021.5.30        py39h06a4308_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
ncurses                   6.2                  he6710b0_1  
openssl                   1.1.1k               h27cfd23_0  
pip                       21.1.1           py39h06a4308_0  
python                    3.9.0                hdb3f193_2  
readline                  8.1                  h27cfd23_0  
setuptools                52.0.0           py39h06a4308_0  
sqlite                    3.35.4               hdfb4753_0  
tk                        8.6.10               hbc83047_0  
tzdata                    2020f                h52ac0ba_0  
wheel                     0.36.2             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3  

### Description of Issue

(try_1) razor@razor-GL502VSK:~/Projects/Exacter/exacter$ pip install --upgrade pyforest
Collecting pyforest
  Using cached pyforest-1.0.3.tar.gz (14 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/razor/anaconda3/envs/try_1/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-u_llula5/pyforest_11acaa30b5264e968fae0ab3e6653f8f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-u_llula5/pyforest_11acaa30b5264e968fae0ab3e6653f8f/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ird11kvt
         cwd: /tmp/pip-install-u_llula5/pyforest_11acaa30b5264e968fae0ab3e6653f8f/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-u_llula5/pyforest_11acaa30b5264e968fae0ab3e6653f8f/setup.py", line 10, in <module>
        from src.pyforest.auto_import import setup as setup_auto_import
    ModuleNotFoundError: No module named 'src.pyforest'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/8f/85/77a9d2d9ff240822039f3dfd7a3b374d0621a0df5feb5d270a2151f6bb6d/pyforest-1.0.3.tar.gz#sha256=0dda455a0f70dc3abdaeee934cc6026b2c8bef5228439095016a08649653d0c3 (from https://pypi.org/simple/pyforest/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached pyforest-1.0.2.tar.gz (14 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/razor/anaconda3/envs/try_1/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-u_llula5/pyforest_7c816f4471294a14b2255ffef062a3b9/setup.py'"'"'; __file__='"'"'/tmp/pip-install-u_llula5/pyforest_7c816f4471294a14b2255ffef062a3b9/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-ygeqaz1b
         cwd: /tmp/pip-install-u_llula5/pyforest_7c816f4471294a14b2255ffef062a3b9/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-u_llula5/pyforest_7c816f4471294a14b2255ffef062a3b9/setup.py", line 10, in <module>
        from src.pyforest.auto_import import setup as setup_auto_import
    ModuleNotFoundError: No module named 'src.pyforest'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ac/c3/ae8976c2c281c69aef2a615e8e3e6ce8c0b401c55dd68c50911d0d532b3b/pyforest-1.0.2.tar.gz#sha256=d61633056fdff32f947fee852b28ae260961175f38447f066ba0c086e74fa332 (from https://pypi.org/simple/pyforest/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached pyforest-1.0.1.tar.gz (13 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/razor/anaconda3/envs/try_1/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-u_llula5/pyforest_c891e6b18a7243a9a30b7a6dc81c9d81/setup.py'"'"'; __file__='"'"'/tmp/pip-install-u_llula5/pyforest_c891e6b18a7243a9a30b7a6dc81c9d81/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-cn5g2na4
         cwd: /tmp/pip-install-u_llula5/pyforest_c891e6b18a7243a9a30b7a6dc81c9d81/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-u_llula5/pyforest_c891e6b18a7243a9a30b7a6dc81c9d81/setup.py", line 10, in <module>
        from src.pyforest.auto_import import setup as setup_auto_import
    ModuleNotFoundError: No module named 'src.pyforest'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/b6/25/0b49ebd345a7f57ef95e7199c46207b7f5b34e61d8c36c77197e35536f95/pyforest-1.0.1.tar.gz#sha256=cbf79626d94c523f202902bb7900f1cc659f09e87991e3df7777f96d073ad123 (from https://pypi.org/simple/pyforest/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached pyforest-1.0.0.tar.gz (12 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/razor/anaconda3/envs/try_1/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-u_llula5/pyforest_181d5a12a22b44d087a26f857330338e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-u_llula5/pyforest_181d5a12a22b44d087a26f857330338e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_7cxq_gh
         cwd: /tmp/pip-install-u_llula5/pyforest_181d5a12a22b44d087a26f857330338e/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-u_llula5/pyforest_181d5a12a22b44d087a26f857330338e/setup.py", line 10, in <module>
        from src.pyforest.auto_import import setup as setup_auto_import
    ModuleNotFoundError: No module named 'src.pyforest'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/d4/6d/86e083e0510b56d1f458735d44cdf181383f2a1ed6c234db7b51e7807e13/pyforest-1.0.0.tar.gz#sha256=eb7703883225aa54cb4d963cb81f0f15c4525cea09dd8c9d441990eb325fd080 (from https://pypi.org/simple/pyforest/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached pyforest-0.1.4.tar.gz (9.4 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/razor/anaconda3/envs/try_1/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-u_llula5/pyforest_ec37a82702064005be816e0a2acc7a0e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-u_llula5/pyforest_ec37a82702064005be816e0a2acc7a0e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-o2_8_5yw
         cwd: /tmp/pip-install-u_llula5/pyforest_ec37a82702064005be816e0a2acc7a0e/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-u_llula5/pyforest_ec37a82702064005be816e0a2acc7a0e/setup.py", line 10, in <module>
        from src.pyforest.auto_import import setup as setup_auto_import
    ModuleNotFoundError: No module named 'src.pyforest'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/07/b7/c78623e4b215b0476f96038cfe75920eda1a9a216fed1e6105a7d9de5e47/pyforest-0.1.4.tar.gz#sha256=ed7db5d2f15b08141b816c961cd82b44769b345fcb8d51f167c91542a0af86c6 (from https://pypi.org/simple/pyforest/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached pyforest-0.1.3.tar.gz (8.4 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/razor/anaconda3/envs/try_1/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-u_llula5/pyforest_7abc73ce4a2d4e68af1305a44183821b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-u_llula5/pyforest_7abc73ce4a2d4e68af1305a44183821b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-14llz_pa
         cwd: /tmp/pip-install-u_llula5/pyforest_7abc73ce4a2d4e68af1305a44183821b/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-u_llula5/pyforest_7abc73ce4a2d4e68af1305a44183821b/setup.py", line 10, in <module>
        from src.pyforest.auto_import import setup as setup_auto_import
    ModuleNotFoundError: No module named 'src.pyforest'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/e5/be/7681d01d5a52ba17254edb362386d0e4fcbd00aec2700ede31fc006bd366/pyforest-0.1.3.tar.gz#sha256=9fa0b48bdddbb7bd0b42edf5d753b44a781202c1d58387b722407295814331ec (from https://pypi.org/simple/pyforest/) (requires-python:>=3.6). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached pyforest-0.1.1.tar.gz (3.4 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/razor/anaconda3/envs/try_1/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-u_llula5/pyforest_b428b46869ee426199b36ae2d47f4c3e/setup.py'"'"'; __file__='"'"'/tmp/pip-install-u_llula5/pyforest_b428b46869ee426199b36ae2d47f4c3e/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-0zd87uny
         cwd: /tmp/pip-install-u_llula5/pyforest_b428b46869ee426199b36ae2d47f4c3e/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-u_llula5/pyforest_b428b46869ee426199b36ae2d47f4c3e/setup.py", line 10, in <module>
        from src.pyforest.auto_import import setup as setup_auto_import
    ModuleNotFoundError: No module named 'src.pyforest'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ca/7a/2280448ba4202604eb3f9e23d9a4fd0ca1473d31aca0a90fdb5f31dd902c/pyforest-0.1.1.tar.gz#sha256=685c904461d192650519ffec8a81c2537b60b63726a8e2b363c2f6695c97337c (from https://pypi.org/simple/pyforest/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached pyforest-0.0.2.tar.gz (3.4 MB)
    ERROR: Command errored out with exit status 1:
     command: /home/razor/anaconda3/envs/try_1/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-u_llula5/pyforest_fc9503bb528b48f190d6ab001c782397/setup.py'"'"'; __file__='"'"'/tmp/pip-install-u_llula5/pyforest_fc9503bb528b48f190d6ab001c782397/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-g4h50u80
         cwd: /tmp/pip-install-u_llula5/pyforest_fc9503bb528b48f190d6ab001c782397/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-u_llula5/pyforest_fc9503bb528b48f190d6ab001c782397/setup.py", line 10, in <module>
        from src.pyforest.auto_import import setup as setup_auto_import
    ModuleNotFoundError: No module named 'src.pyforest'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/e3/fb/af7ac4428a43cc114b1eb9c50ba608501bc99f538dbc56331bfd6f7bcaa9/pyforest-0.0.2.tar.gz#sha256=6cdf75e0e7f9760a2c964115038abbda298b1daeb749ff52249816cae37b20b5 (from https://pypi.org/simple/pyforest/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement pyforest (from versions: 0.0.2, 0.1.1, 0.1.3, 0.1.4, 1.0.0, 1.0.1, 1.0.2, 1.0.3)
ERROR: No matching distribution found for pyforest

* What did you expect to happen? Install pyforest
* What happened instead? Didn't install

### Reproduction Steps

1.pip install --upgrade pyforest
...

### What steps have you taken to resolve this already?
Couldn't
...

### Anything else?

...

**Comment by tkrabel** [comment]
Thanks for reporting the issue.

I installed pyforest successfully using docker with python 3.9

Does this Dockerfile work with you too?

```bash
FROM jupyter/minimal-notebook
RUN pip install --upgrade pyforest
```

If so, my WASG is that this is a problem specific to your setup (probably an anaconda3 issue?).

**Comment by mehak-sood** [comment]
I have the same error trying to install pyforest in the Conda environment with 

pip install pyforest 

conda install --upgrade pyforest.

```
Collecting pyforest
  Using cached pyforest-1.1.0.tar.gz (15 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/j6/5m8wm88d6853jw0c3cp9sbr00000gn/T/pip-install-pyoywfer/pyforest_b66c894e97544b56940b5cabe40f0a84/setup.py", line 10, in <module>
          from src.pyforest.auto_import import setup as setup_auto_import
      ModuleNotFoundError: No module named 'src.pyforest'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by tkrabel** [comment]
@mehak-sood I made a new release. Does it work now?
